# The stanford_travisci_scripts repository contains external scripts
# used here to configure server and build a self-service site.
# https://github.com/SU-SWS/stanford_travisci_scripts

env:
  # Enter the name of this repository, ie. stanford_bean_types
  - REPOSITORY_NAME=""
  # Leave PRODUCT_NAME blank to install a self-service site
  # Or enter the product you would like to build, ie. jumpstart-academic
  - PRODUCT_NAME=""
  # Enter as a space separated string, modules you need that might not be enabled by default
  # ie. stanford_gallery nobots
  - ENABLE_MODULES="stanford_events_importer stanford_events_export stanford_events_views stanford_events_and_deadlines_calendar feeds_ui"
  # Enter as a space separated string, modules you need disabled
  - DISABLE_MODULES="webauth"
  # Leave blank to use the default stanford-jumpstart-deployer branch
  - DEPLOYER_BRANCH=""
  # Leave blank to use the default Stanford-Drupal-Profile branch
  - DRUPAL_PROFILE_BRANCH=""
  # Leave blank to use the default linky_clicky branch
  - CLICKY_BRANCH="HSDO-593-recap-tests"
  # Leave blank to use the default stanford_travisci_scripts branch
  - SCRIPTS_BRANCH=""

language: php
php:
  - '5.6'

sudo: required

cache:
  directories:
    - $HOME/.cache
    - $HOME/.composer/cache
    - $HOME/.drush/cache

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  # download external repository with Stanford Travis CI scripts
  - if [ ! -z $SCRIPTS_BRANCH ]; then SCRIPTS_BRANCH="-b $SCRIPTS_BRANCH"; fi
  - git clone $SCRIPTS_BRANCH https://github.com/SU-SWS/stanford_travisci_scripts.git $HOME/stanford_travisci_scripts
  - chmod +x $HOME/stanford_travisci_scripts/bin/*.sh
  # install composer packages
  - $HOME/stanford_travisci_scripts/bin/before_install.sh

install:
  # install self-service site, disable webauth module, start webserver and selenium webdriver
  - $HOME/stanford_travisci_scripts/bin/install.sh

before_script:
  # download linky_clicky, grab related tests, and start xvfb virtual display
  - $HOME/stanford_travisci_scripts/bin/before_script.sh

script:
  # make sure shell can find drush and run behat tests here, so Travis CI reports accurate results
  - $HOME/stanford_travisci_scripts/bin/script.sh
