<?php
/**
 * @file
 * Code for the Stanford Events Importer feature.
 */

include_once('stanford_events_importer.features.inc');

/*
 * Implements hook_help().
 */
function stanford_events_importer_help($path, $arg) {
  switch ($path) {
    case 'admin/help#stanford_events_importer':
      $output = '<h2>' . t('To Use') . '</h2>';
      $output .= '<ol><li>' . t('Enable the module and all dependencies') . '</li>';
      $output .= '<li>' . t('Go to !permissions and give selected roles the following permissions:', array('!permissions' => l('admin/people/permissions', 'admin/people/permissions')));
      $output .= '<ul><li>' . t('Import Stanford Event Importer feeds ') . '</li><li>' . t('Stanford Event: Create new content') . '</li><li>' . t('Stanford Event Importer: Create new content ') . '</li></ul></li>';
      $output .= '<li>' . t('!addnode of the type "Stanford Event Importer". Give it a title (eg, "Featured Events") and a feed URL (eg, !feedurl)', array('!addnode' => l('Create a new node', 'node/add/stanford-event-importer'), '!feedurl' => l('http://events.stanford.edu/xml/drupal/v2.php?featured', 'http://events.stanford.edu/xml/drupal/v2.php?featured')));
      $output .= '<ul><li>' . t('Full documentation of the Stanford Events Drupal Feed Service is available at !eventsdrupal', array('!eventsdrupal' => l('http://events.stanford.edu/xml/drupal/', 'http://events.stanford.edu/xml/drupal/'))) . '</li></ul></li>';
      $output .= '<li>' . t('Your events will be imported') . '</li>';
      $output .= '<li>' . t('You can set refresh rate and other options at !editimporter (requires enabling the Feeds UI module)', array('!editimporter' => l('admin/build/feeds/edit/stanford_event_importer', 'admin/build/feeds/edit/stanford_event_importer'))) . '</li></ol>';
      return $output;
  }
}

/*
 * Implements hook_form_FORM_ID_alter().
 */
function stanford_events_importer_form_stanford_event_importer_node_form_alter(&$form, &$form_state, $form_id) {
  $form['feeds']['#access'] = FALSE;
  $query = db_select('stanford_events_category_list', 'c');
  $query->fields('c', array('category_id', 'name'));
  $result = $query->execute();
  $categories = $result->fetchAllKeyed();
  asort(&$categories);
  $query = db_select('stanford_events_organization_list', 'o');
  $query->fields('o', array('organization_id', 'name'));
  $result = $query->execute();
  $organizations = $result->fetchAllKeyed();
  asort(&$organizations);
  $form['stanford_events_category'] = array (
    '#type' => 'select',
    '#options' => $categories,
    '#title' => t('Category'),
    '#description' => t('Select a category'),
  );
  $form['stanford_events_organization'] = array (
    '#type' => 'select',
    '#options' => $organizations,
    '#title' => t('Organization'),
    '#description' => t('Select an organization'),
  );
  //dpm($form);
}
