<?php

/**
 * @file
 * Code for the Stanford Events Recap feature.
 */

include_once 'stanford_events_recap.features.inc';

/**
 * Implements hook_preprocess_field().
 */
function stanford_events_recap_preprocess_field(&$vars) {
  switch ($vars['element']['#field_name']) {
    case 'field_s_event_post_recap':
      drupal_add_css(drupal_get_path('module', 'stanford_events_recap') . '/css/stanford_events_recap.css');
      break;
  }
}
